dependencies:
  build:
    - ruby:2.3.4

build_targets:
  - name: default
    container: 
      image: yourbase/yb_ubuntu:18.04
    commands:
        - chmod +x yourbased.sh
        - ./yourbased.sh
    environment:
      - TEST_GROUP=./script/check_syntax
     
ci:
  builds:
    - name: default
      build_target: default
